### ISSUE TITLE
Make the guest interface very similar to existing scheduler plugins interface

### ISSUE THREAD

**Issue by sanposhiho** [kubernetes-sigs/kube-scheduler-wasm-extension#15]
**What would you like to be added**:

people can implement wasm based plugins in very similar interface of the [plugins](https://github.com/kubernetes/kubernetes/blob/master/pkg/scheduler/framework/interface.go#L303-L505) in scheduling framework.

**Why is this needed**:

You can see how to implement the guest in the [example](https://github.com/kubernetes-sigs/kube-scheduler-wasm-extension/blob/main/example/main.go).
It's now quite different from how we implement the scheduler plugins.

To reduce the learning cost for people and to make it easy to convert from existing plugins to wasm-based plugins, we want to reduce the difference from [the scheduler's plugin interface](https://github.com/kubernetes/kubernetes/blob/master/pkg/scheduler/framework/interface.go#L303-L505) as much as possible.

**Completion requirements**:

This enhancement requires the following artifacts:

- [ ] Design doc
- [ ] API change
- [ ] Docs update

The artifacts should be linked in subsequent comments.

**Comment by codefromthecrypt** [comment]
dependent on  #13, but sounds good

**Comment by sanposhiho** [comment]
/close

I now know it's a quite bad/impossible idea to make both interface same. We can come back here when the allocation or GC performance gets improved, but for now, just close it

**Comment by codefromthecrypt** [comment]
ps this makes things closer, and the important thing is benchmark driven and still get a lot closer to the host interface. https://github.com/kubernetes-sigs/kube-scheduler-wasm-extension/pull/32
