### ISSUE TITLE
Support all extension points

### ISSUE THREAD

**Issue by sanposhiho** [kubernetes-sigs/kube-scheduler-wasm-extension#72]
- [x] EnqueueExtensions (without hint)
- [ ] EnqueueExtensions (with hint)
- [x] PreFilterExtensions @chansuke 
- [x] PreFilterPlugin
- [x] FilterPlugin
- [x] PreScorePlugin
- [x] ScorePlugin
- [x] ScoreExtensions @Gekko0114 
- [x] PostFilterPlugin @Gekko0114 
- [x] ReservePlugin @utam0k 
- [x] PermitPlugin @kazukousen 
- [x] PreBindPlugin @Gekko0114 
- [x] BindPlugin @Gekko0114 
- [x] PostBindPlugin @Gekko0114 

---

Note that this issue's scope is only the interface support. 
For example, you may think that PostFilterPlugin is useless unless some functions in `framework.Handle` is supported. That might be true, but https://github.com/kubernetes-sigs/kube-scheduler-wasm-extension/issues/73 does the support, not this issue.

**Comment by sanposhiho** [comment]
I'll take `ScoreExtensions`.

**Comment by Gekko0114** [comment]
@sanposhiho ,
Can I work on PostFilterPlugin?

**Comment by sanposhiho** [comment]
Yes.

/assign @Gekko0114

**Comment by Gekko0114** [comment]
I'll work on ScoreExtensions as well

**Comment by sanposhiho** [comment]
@Gekko0114 Excellent, assigned it to you.
Sorry for the delay on reviews, I think I'll be able to have time in this weekend.

**Comment by Gekko0114** [comment]
Since implementing extension points is interesting for me, I will work on PreBindPlugin :)
(Please let me know if you have any comments)

**Comment by Gekko0114** [comment]
PreBindPlugin's implementation partially depends on bindPlugin, so I will implment BindPlugin at the same time

**Comment by Gekko0114** [comment]
Thanks for your review!
I will work on PostBindPlugin as well

**Comment by utam0k** [comment]
I'm newer in this field, but I'm interested in contributing to this issue. Can I pick up PreBind?

**Comment by Gekko0114** [comment]
I completed prebind, so remaining item is reserve plugin I guess

**Comment by utam0k** [comment]
@Gekko0114 Wow! You work very hard! Okay, can I pick the Revere plugin? I don't know if this one is suitable for the beginner... 🤔

**Comment by utam0k** [comment]
@sanposhiho Which one is good for the first step?

**Comment by sanposhiho** [comment]
Tabun Reserve.

**Comment by utam0k** [comment]
Please assign me to Reserver plugin😆

**Comment by Gekko0114** [comment]
BTW we may miss permit plugin?

**Comment by sanposhiho** [comment]
🦀 Added.

**Comment by sanposhiho** [comment]
My interest has actually moved to #71, I'll leave PreFilterExtensions for someone else.

**Comment by chansuke** [comment]
I would like to work on `PreFilterExtensions`🤲🏻

**Comment by sanposhiho** [comment]
assigned 🤲🏻

**Comment by kazukousen** [comment]
Can I work on PermitPlugin ?

**Comment by sanposhiho** [comment]
Yes.

/assign @kazukousen @chansuke

**Comment by sanposhiho** [comment]
@kazukousen 

Look at other people's PR to get what's needed for PermitPlugin, e.g., https://github.com/kubernetes-sigs/kube-scheduler-wasm-extension/pull/82
Communicate in English in public (issues/PRs), and if you have a question, you can reach out to me or @Gekko0114 in the Kubernetes slack, and obviously Japanese is OK in DM if you want :)

- K8s slack:  https://communityinviter.com/apps/kubernetes/community
