### ISSUE TITLE
Test framework support

### ISSUE THREAD

**Issue by kerthcet** [kubernetes-sigs/kube-scheduler-wasm-extension#8]
**What would you like to be added**:

We should have a test framework to run test suit each time we have new PRs.
This requires the support from [test infra](https://github.com/kubernetes/test-infra)

**Why is this needed**:

Project health and stability

**Completion requirements**:

This enhancement requires the following artifacts:

- [ ] Design doc
- [ ] API change
- [ ] Docs update

The artifacts should be linked in subsequent comments.

**Comment by codefromthecrypt** [comment]
Is this different than normal CI for unit tests?

**Comment by sanposhiho** [comment]
Let's prioritize it.
/priority important-soon

@kerthcet Could you work on it? 🙏

**Comment by kerthcet** [comment]
Yes
/assign

**Comment by codefromthecrypt** [comment]
here is basic CI, we had several source files that were checked in even though they didn't compile https://github.com/kubernetes-sigs/kube-scheduler-wasm-extension/pull/30

**Comment by kerthcet** [comment]
I did some research this weekend, the testgrid will read junit.xml artifacts for display. However we have multi modules, we can't generate a unified test report cover all the packages, it's a little tricky.

**Comment by pohly** [comment]
I'm not sure about the exact pattern, but I think Spyglass and testgrid read all junit*.xml files in the artifacts directory. You should be able to write one file per package.
