### ISSUE TITLE
setup scheduler with the wasm extension

### ISSUE THREAD

**Issue by sanposhiho** [kubernetes-sigs/kube-scheduler-wasm-extension#9]
**What would you like to be added**:

```[tasklist]
### Tasks
- [x] create the scheduler with the wasm extension
- [x] create `registry.k8s.io/kube-scheduler-wasm-extension/scheduler` to provide the scheduler in which the wasm extension is enabled
```

**Why is this needed**:

We will eventually try to include this wasm extension into the upstream, but it's worth having the scheduler binary/image here meanwhile regardless.

I'll work on this since I recently worked on the registry stuff in the simulator and understand the process.

/assign
/cc @kerthcet

**Comment by sanposhiho** [comment]
I meant building the scheduler with our [wasm extension plugin](https://github.com/kubernetes-sigs/kube-scheduler-wasm-extension/blob/main/plugin/plugin.go)
Just like scheduler-plugins does: https://github.com/kubernetes-sigs/scheduler-plugins/blob/master/cmd/scheduler/main.go

**Comment by kerthcet** [comment]
Got it, plz go ahead.

**Comment by Gekko0114** [comment]
/lgtm
Thanks!

**Comment by sanposhiho** [comment]
Still there is a remaining step for the registry.
