### ISSUE TITLE
First release: v0.1.0

### ISSUE THREAD

**Issue by sanposhiho** [kubernetes-sigs/kube-scheduler-wasm-extension#91]
This issue proposes our first release of v0.1.0. 
It'll be after all [prioirty/next-release](https://github.com/kubernetes-sigs/kube-scheduler-wasm-extension/labels/priority%2Fnext-release) are done.

**Comment by utam0k** [comment]
🚀

**Comment by novohool** [comment]
https://github.com/ktock/container2wasm

**Comment by sanposhiho** [comment]
/assign
(I'll go thru a release process)

**Comment by sanposhiho** [comment]
https://github.com/kubernetes-sigs/kube-scheduler-wasm-extension/releases/tag/v0.1.0
