### ISSUE TITLE
github action `testdata` might have a issue.

### ISSUE THREAD

**Issue by Gekko0114** [kubernetes-sigs/kube-scheduler-wasm-extension#97]
**What happened**:
There might be several issues.
1 `testdata` action might not fail because there is no command checking if the PR includes all wasm files, like `git diff --exit-code`.
2 However, introducing a command like `git diff --exit-code` might lead to a new problem. wasm files seem to depend on developer's environment. For example, I am using mac environment. Even though I don't change any codes, wasm file I build is different from the file attached in the github repo. If we implement a command like `git diff --exit-code`, we might need to standardize the development environment.

Please let me know if I misunderstand something.

(Previously I talked this issue with @kazukousen)

**What you expected to happen**:

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
github_actions

**Comment by sanposhiho** [comment]
> github action testdata might have a issue

@Gekko0114 Can you investigate if it does have or not when get a chance?
